name: MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t iris-classifier .

    - name: Train the model
      run: docker run -v $(pwd):/app iris-classifier

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test the model
      run: docker run -v $(pwd):/app iris-classifier python -c "import joblib; model = joblib.load('model.pkl'); print(model.predict([[5.1, 3.5, 1.4, 0.2]]))"

